encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:title>", views.entry, name="info"),
    path("wiki/search/", views.search, name="search"),
    path("wiki/create/", views.create, name="create"),
    path("wiki/message/<str:message>", views.message, name="message"),
    path("wiki/<str:title>/edit", views.edit, name="edit"),
    path("wiki/random/", views.random_page, name="random_page")
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
import markdown2
import random
from django.http import HttpResponse
from django.shortcuts import render, redirect

from . import util

def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })


def entry(request, title):
    # Use the get_entry function to retrieve the entry content
    entry_content = util.get_entry(title)

    if entry_content is None:
        return redirect('encyclopedia:message', message="The requested page was not found.")

    # Convert Markdown to HTML
    html_content = markdown2.markdown(entry_content)

    return render(request, "encyclopedia/entry.html", {
        "html_content": html_content,
        "title": title
    })


def search(request):
    # Retrieve the query from the GET request
    query = request.GET.get('q', '')

    # Retrieve all entry names
    entries = util.list_entries()

    results = []
    
    if query:
        # Check for an exact match
        for entry in entries:
            if query.lower() == entry.lower():
                return redirect('encyclopedia:info', title=entry)
            
        # If no exact match, find entries that contain the query as a substring
        results = [entry for entry in entries if query.lower() in entry.lower()]

    return render(request, "encyclopedia/search.html", {
        "query": query, 
        "results": results
    })


def create(request):
    if request.method == "POST":
        title = request.POST.get('title')
        content = request.POST.get('content')

        if util.get_entry(title) is not None:
            return redirect('encyclopedia:message', message="An entry with this title already exists.")
        
        util.save_entry(title, content)
        return redirect('encyclopedia:info', title=title)
    
    return render(request, "encyclopedia/create.html")


def edit(request, title):
    if request.method == 'POST':
        # Save changes
        content = request.POST['content']
        util.save_entry(title, content)
        return redirect('encyclopedia:info', title=title)
    
    content = util.get_entry(title)

    if content is None:
        return redirect('encyclopedia:message', message="The requested page was not found.")
    
    return render(request, "encyclopedia/edit.html", {
        "title": title,
        "content": content
    })


def random_page(request):
    entries = util.list_entries()
    if not entries:
        return redirect('encyclopedia:message', message="No entries available.")
    title = random.choice(entries)
    return redirect('encyclopedia:info', title=title)

def message(request, message):
    return render(request, "encyclopedia/message.html", {
        "message": message
    })

encyclopedia/templates/encyclopedia/create.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Create New Page
{% endblock %}

{% block body %}

    <h1>Create New Page</h1>

    <form action="{% url 'encyclopedia:create' %}" method="post">
        {% csrf_token %}
        <input type="text" name="title" placeholder="Title" autocomplete="off" required>
        <textarea name="content" id="createContent" required></textarea>
        <br>
        <input type="submit" value="Save">
    </form>

{% endblock %}

encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Edit: {{ title }}
{% endblock %}

{% block body %}
    <h1>Edit: {{ title }}</h1>

    <form action="{% url 'encyclopedia:edit' title=title %}" method="post">
        {% csrf_token %}
        <textarea name="content" id="editContent">{{ content }}</textarea>
        <br>
        <input type="submit" value="Save Changes">
    </form>
{% endblock %}

encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia: {{ title }}
{% endblock %}

{% block body %}
    <div class="title">
        <h1>{{ title }}</h1>
    </div>

    {{ html_content|safe }}

    <a href="{% url 'encyclopedia:edit' title=title %}">Edit this page</a>

{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li>
                <a href="{% url 'encyclopedia:info' entry %}">
                    {{ entry }}
                </a>
            </li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>

                <form action="{% url 'encyclopedia:search' %}" method="get">
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia" autocomplete="off">
                </form>

                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:create' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:random_page' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/message.html
{% extends "encyclopedia/layout.html" %}

{% block body %}

    <div class="error">
        <h1>Error Message</h1>
    </div>

    <h3>{{ message }}</h3>

{% endblock %}

encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Search Results: {{ query }}
{% endblock %}

{% block body %}

    <h1>Search Results for "{{ query }}"</h1>

    {% if results %}
        <ul>
            {% for entry in results %}
                <li><a href="{% url 'encyclopedia:info' title=entry %}">{{ entry }}</a></li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No results found.</p> 
    {% endif %}

{% endblock %}